"""runtime.helpers package — re-export of all submodules."""

from runtime.helpers._channels import (  # noqa: F401
    _author_msg_kwargs,
    _channel_config_by_key,
    _channel_conversation_scope,
    _channel_msg_kwargs,
    _channel_reply_target_name,
    _channel_scope,
    _get_channel_behavior,
    _get_singleton_channel,
    _get_singleton_channel_id,
    _is_bot_mentioned,
    _leading_bot_mention_pattern,
    _reply_text,
    _safe_reply,
    _share_channel_result,
    _strip_bot_mentions,
)
from runtime.helpers._common import (  # noqa: F401
    BOT_ROLE_ID,
    CHICAGO,
    DISCORD_CHUNK_SIZE,
    DISCORD_MAX_MESSAGE_LEN,
    LEADER_ROLE_ID,
    _bare_tag,
    _bot,
    _bot_role_id,
    _chicago,
    _chunk_for_discord,
    _fmt_bytes,
    _fmt_iso_short,
    _fmt_num,
    _fmt_relative,
    _format_relative_join_age,
    _job_next_runs,
    _join_member_bits,
    _leader_role_id,
    _leader_role_mention,
    _log,
    _member_label,
    _recent_join_display_rows,
    _runtime_app,
    _safe_create_task,
    _schedule_specs,
    _scheduler,
    _status_badge,
    _with_leader_ping,
    bot,
    log,
    scheduler,
)

# _post_to_elixir is a delegation wrapper in _common.py that forwards to
# runtime.app — excluded to avoid recursion when accessed via the top-level
# elixir module.
from runtime.helpers._members import (  # noqa: F401
    _build_member_deck_report,
    _build_member_war_decks_report,
    _extract_member_deck_target,
    _match_clan_member,
    _resolve_member_candidate,
)
from runtime.helpers._reports import (  # noqa: F401
    _DB_STATUS_MEMORY_TABLES,
    _WEEKLY_RECAP_HEADER_RE,
    _build_clan_status_report,
    _build_clan_status_short_report,
    _build_db_status_report,
    _build_help_report,
    _build_kick_risk_report,
    _build_roster_join_dates_report,
    _build_schedule_report,
    _build_status_report,
    _build_top_war_contributors_report,
    _build_war_status_report,
    _build_weekly_clan_recap_context,
    _db_status_group_for_table,
    _db_status_group_label,
    _format_weekly_recap_post,
    _load_live_clan_context,
    _strip_weekly_recap_header,
    build_lane_memory_context,
    format_weekly_recap_email,
)
from runtime.helpers._requests import (  # noqa: F401
    _fallback_channel_response,
)
